CREATE TABLE `t_postprocessing` (
  `logid` char(32) NOT NULL COMMENT '日志记录主键',
  `createtime` datetime DEFAULT NULL COMMENT '记录创建时间',
  `stuuid` char(64) DEFAULT NULL COMMENT '检查UID',
  `srsuid` char(64) DEFAULT NULL COMMENT '序列UID',
  `imguid` char(64) DEFAULT NULL COMMENT '图像UID',
  `command` varchar(32) DEFAULT NULL COMMENT '用户选择的后处理功能',
  `param01` varchar(32) DEFAULT NULL COMMENT '后处理功能的参数',
  `param02` varchar(32) DEFAULT NULL,
  `param03` varchar(32) DEFAULT NULL,
  `param04` varchar(32) DEFAULT NULL,
  `param05` varchar(32) DEFAULT NULL,
  `param06` varchar(32) DEFAULT NULL,
  `param07` varchar(32) DEFAULT NULL,
  `param08` varchar(32) DEFAULT NULL,
  `param09` varchar(32) DEFAULT NULL,
  `param10` varchar(45) DEFAULT NULL,
  `param11` varchar(32) DEFAULT NULL,
  `param12` varchar(32) DEFAULT NULL,
  `param13` varchar(32) DEFAULT NULL,
  `param14` varchar(32) DEFAULT NULL,
  `param15` varchar(32) DEFAULT NULL,
  `param16` varchar(32) DEFAULT NULL,
  `exefile` varchar(512) DEFAULT NULL COMMENT '后处理软件的可执行文件名称',
  `imagefile` varchar(512) DEFAULT NULL COMMENT '输入影像文件的目录和名称',
  `outputfile` varchar(512) DEFAULT NULL COMMENT '输出影像文件的目录和名称',
  `result` char(1) DEFAULT '0' COMMENT '后处理运算结果：0-成功，1-失败',
  `remark1` varchar(45) DEFAULT NULL COMMENT '备用字段',
  `remark2` varchar(45) DEFAULT NULL,
  `remark3` varchar(45) DEFAULT NULL COMMENT '备用字段',
  `remark4` varchar(45) DEFAULT NULL,
  `remark5` varchar(45) DEFAULT NULL COMMENT '备用字段',
  `remark6` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`logid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='影像文件后处理过程记录'