
package com.inteall.image.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
   ObjectFactory.class
})
public interface WSSoap {


    /**
     * 
     * @param content
     * @param pwd
     * @param cell
     * @param sendTime
     * @param corpID
     * @param mobile
     * @return
     *     returns long
     */
    @WebMethod(operationName = "Send", action = "http://tempuri.org/Send")
    @WebResult(name = "SendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.Send")
    @ResponseWrapper(localName = "SendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.SendResponse")
    public long send(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * <h3>Ⱥ������</h3>CorpID:�˺�,Pwd:����,Mobile:�ֻ����봮,Content:��������,Cell:�Ӻ�(��Ϊ��),SendTime:����ʱ��(��Ϊ��)<br/>����ֵ������0Ϊ�ύ��ˮ��(��־�ύ�ɹ�)  �C1	�˺�δע�� �C2	�������� �C3	�ʺŻ��������  �C4	һ���ύ��Ϣ���ܳ���10000���ֻ����룬���붺�Ÿ��� �C5	���㣬���ȳ�ֵ �C6	��ʱ����ʱ�䲻����Ч��ʱ���ʽ �C8	������������3��250��֮��  -9	���ͺ���Ϊ�� 
     * 
     * @param content
     * @param pwd
     * @param cell
     * @param sendTime
     * @param corpID
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BatchSend", action = "http://tempuri.org/BatchSend")
    @WebResult(name = "BatchSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BatchSend", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.BatchSend")
    @ResponseWrapper(localName = "BatchSendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.BatchSendResponse")
    public String batchSend(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        String content,
        @WebParam(name = "Cell", targetNamespace = "http://tempuri.org/")
        String cell,
        @WebParam(name = "SendTime", targetNamespace = "http://tempuri.org/")
        String sendTime);

    /**
     * <h3>�˺�����ѯ</h3>CorpID:�˺�,Pwd:���� <br/>����ֵ�����ڵ���0Ϊ�˺����  �C1	�˺�δע�� �C2	�������� �C3	�ʺŻ�������� 
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SelSum", action = "http://tempuri.org/SelSum")
    @WebResult(name = "SelSumResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SelSum", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.SelSum")
    @ResponseWrapper(localName = "SelSumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.SelSumResponse")
    public String selSum(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * <h3>ȡ���ж���</h3>CorpID:�˺�,Pwd:���� <br/>����ֵ�� ||�ֻ���#��������#����ʱ��#�Ӻ�||�ֻ���#��������#����ʱ��#�Ӻš�   �C1	�˺�δע�� �C2	�������� �C3	�ʺŻ�������� 
     * 
     * @param pwd
     * @param corpID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get", action = "http://tempuri.org/Get")
    @WebResult(name = "GetResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.Get")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.GetResponse")
    public String get(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * <h3>ȡ�����������ж���</h3>CorpID:�˺�,Pwd:���� Phone�������ֻ��� <br/>����ֵ�� ||�ֻ���#��������#����ʱ��#�Ӻ�||�ֻ���#��������#����ʱ��#�Ӻš�   �C1	�˺�δע�� �C2	�������� �C3 �ʺŻ��������  -4�ֻ����쳣
     * 
     * @param phone
     * @param pwd
     * @param corpID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOne", action = "http://tempuri.org/GetOne")
    @WebResult(name = "GetOneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOne", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.GetOne")
    @ResponseWrapper(localName = "GetOneResponse", targetNamespace = "http://tempuri.org/", className = "org.tempeuri2.GetOneResponse")
    public String getOne(
        @WebParam(name = "CorpID", targetNamespace = "http://tempuri.org/")
        String corpID,
        @WebParam(name = "Pwd", targetNamespace = "http://tempuri.org/")
        String pwd,
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        String phone);

}
