CREATE TABLE `t_consultation` (
  `case_id` varchar(32) NOT NULL COMMENT '会诊病历主索引',
  `image_id` varchar(32) NOT NULL COMMENT '影像文件外键',
  `opinion_id` varchar(32) NOT NULL COMMENT '会诊意见书外键',
  `state` char(1) NOT NULL DEFAULT '1' COMMENT '业务过程状态：1-未提交、2-待会诊、3-申请驳回、4待初审、5--初审驳回、6-待终审、7-终审驳回、8-已完成',
  `modify_time` datetime DEFAULT NULL COMMENT '上一次业务状态变更的时间',
  `create_person` varchar(32) NOT NULL COMMENT '病历创建人外键',
  `create_time` datetime NOT NULL COMMENT '病历创建/上传时间',
  `commit_time` datetime DEFAULT NULL COMMENT '申请提交时间',
  `commit_type` char(1) DEFAULT '1' COMMENT '申请提交类别：1-个人、2-群组',
  `commit_target_person` varchar(32) DEFAULT NULL COMMENT '申请提交目标的用户ID',
  `commit_request` text COMMENT '会诊要求或患者病史信息',
  `accept_person` varchar(32) DEFAULT NULL COMMENT '接受会诊申请人外键',
  `accept_time` datetime DEFAULT NULL COMMENT '接受会诊申请时间',
  `reject_time` datetime DEFAULT NULL COMMENT '申请驳回时间',
  `reject_reason` text COMMENT '申请驳回的理由',
  `primary_audit_person` varchar(32) DEFAULT NULL COMMENT '初审人外键',
  `primary_time` datetime DEFAULT NULL COMMENT '初审完成时间',
  `primary_suggestion` char(1) DEFAULT '0' COMMENT '初审人意见:1-通过,0-驳回',
  `primary_reject` text COMMENT '初审驳回理由',
  `ultimate_audit_person` varchar(32) DEFAULT NULL COMMENT '终审人外键',
  `ultimate_time` datetime DEFAULT NULL COMMENT '终审完成时间',
  `ultimate_suggestion` char(1) DEFAULT '0' COMMENT '终审人意见:1-通过,0-驳回',
  `ultimate_reject` text COMMENT '终审驳回理由',
  `video_state` char(1) DEFAULT '0' COMMENT '视频会诊状态：0-无视频会诊，1-已预约视频会诊',
  `video_time` datetime DEFAULT NULL COMMENT '视频会诊预约时间',
  `video_duration` int(11) DEFAULT '0' COMMENT '视频会诊计划时长，单位：分钟',
  `video_conventioneer` text COMMENT '视频会诊与会人员列表(ID)',
  `is_del` char(1) DEFAULT '0' COMMENT '病历删除标记：0-未删除，1-已删除',
  `del_time` datetime DEFAULT NULL COMMENT '病历删除时间',
  `consultation_remark1` varchar(64) DEFAULT NULL COMMENT '备注信息1',
  `consultation_remark2` varchar(64) DEFAULT NULL COMMENT '备注信息2',
  `consultation_remark3` varchar(64) DEFAULT NULL COMMENT '备注信息3',
  `consultation_remark4` varchar(64) DEFAULT NULL COMMENT '备注信息4',
  `consultation_remark5` varchar(64) DEFAULT NULL COMMENT '备注信息5',
  `consultation_remark6` varchar(64) DEFAULT NULL COMMENT '备注信息6',
  PRIMARY KEY (`case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='远程会诊病历列表'