CREATE TABLE `t_zoom` (
  `zoom_key` varchar(32) NOT NULL COMMENT '主键',
  `state` char(1) NOT NULL DEFAULT '0' COMMENT '日程状态：0-未预约，1-已预约，2-进行中，3-已结束，8-预约失败，9-启动失败',
  `modify_time` datetime DEFAULT NULL COMMENT '最后一次变更时间',
  `create_person` varchar(32) DEFAULT NULL COMMENT '会议日程创建人',
  `create_time` datetime DEFAULT NULL COMMENT '会议日程创建时间',
  `function_type` char(1) DEFAULT NULL COMMENT '业务类型：1-视频会诊，2-读片会，3-视频教学',
  `function_id` varchar(32) DEFAULT NULL COMMENT '业务外键，指向业务数据表',
  `participants` text COMMENT '参会者ID列表',
  `meeting_capacity` int(11) DEFAULT '0' COMMENT '参会人数',
  `minute` int(11) DEFAULT '0' COMMENT '持续时间/会议时长',
  `start_time` datetime DEFAULT NULL COMMENT '计划开始时间',
  `topic` varchar(64) DEFAULT 'InteallMeeting' COMMENT '会议主题',
  `create_url` text COMMENT '生成的提交给ZOOM的创建会议命令',
  `create_result` text COMMENT 'ZOOM返回的创建会议结果',
  `start_url` text COMMENT '主持人加入会议的链接',
  `join_url` text COMMENT '参会人加入会议的链接',
  `id` varchar(16) DEFAULT NULL COMMENT 'App 端用来获取会议ID 的参数',
  `value` varchar(64) DEFAULT NULL COMMENT 'App 端用来获取会议ID 的参数',
  `end_time` datetime DEFAULT NULL COMMENT '计划中会议的结束时间',
  `get_url` text COMMENT '获取移动端uid的命令',
  `get_result` text COMMENT '获取移动端uid的反馈',
  `uid` varchar(16) DEFAULT NULL COMMENT '用户id',
  `token` varchar(64) DEFAULT NULL COMMENT '用户token',
  `update_url` text COMMENT '修改会议人数和主题的链接',
  `update_result` text COMMENT '修改会议人数和主题的反馈',
  `delete_url` text COMMENT '删除预约日程的链接',
  `delete_result` text COMMENT '删除预约日程的反馈',
  `end_url` text COMMENT '强制结束会议的链接',
  `end_result` text COMMENT '强制结束会议的结果',
  `log_url` text COMMENT '获取会议日志命令链接',
  `log_result` text COMMENT '获取会议日志反馈结果',
  `end_timed` datetime DEFAULT NULL COMMENT '会议实际结束时间',
  `meeting_sum_time` int(11) DEFAULT '0' COMMENT '会议总时长',
  `error_code` varchar(32) DEFAULT NULL COMMENT '反馈的错误代码',
  `is_del` char(1) DEFAULT '0' COMMENT '删除标记：0-未删除，1-已删除',
  `del_time` datetime DEFAULT NULL COMMENT '删除时间',
  `zoom_remark1` varchar(64) DEFAULT NULL COMMENT '备注信息1',
  `zoom_remark2` varchar(64) DEFAULT NULL COMMENT '备注信息2',
  `zoom_remark3` varchar(64) DEFAULT NULL COMMENT '备注信息3',
  `zoom_remark4` varchar(64) DEFAULT NULL COMMENT '备注信息4',
  `zoom_remark5` varchar(64) DEFAULT NULL COMMENT '备注信息5',
  `zoom_remark6` varchar(64) DEFAULT NULL COMMENT '备注信息6',
  PRIMARY KEY (`zoom_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ZOOM视频会议日程管理表'